### ISSUE TITLE
Conversion option 'Split to rows' generates less data when turned-off.

### ISSUE THREAD

**Issue by alistairsmarter** [riuson/lcd-image-converter#40]
Hello,

I require my data output on a single line, however, when I deselect 'Split to rows' under the Image tab in Conversion Options, data is single row but less bytes are generated, resulting in an incorrectly displayed image.

Many thanks

**Comment by riuson** [comment]
Hello,
Please, provide:
- small sample image file;
- preset, exported to xml file;
- actual result;
- desired result.
