### ISSUE TITLE
Font optimize height bug

### ISSUE THREAD

**Issue by kosthala** [riuson/lcd-image-converter#44]
Steps to reproduce the bug:

1. Create a new font (File->New Font).
2. Select antialiasing option (Parameters->Antialiasing )
3. Set back color alpha channel to 0.

Now, if you try to optimize the font height (Font->Optimize height...) every character is screwed.
See attached image.
![optimizeheightbug](https://cloud.githubusercontent.com/assets/24932576/21673529/0d56a7ca-d332-11e6-8a6b-0d779594e232.png)

**Comment by riuson** [comment]
Please check a new version.

**Comment by kosthala** [comment]
Hello Vladimir,


I have made a few tests and everything seems to be OK.

Thank you very much for the fix.


Konstantinos.




On 16/01/2017 at 15:24, Vladimir <notifications@github.com> wrote: 
Please check a new version.

**Comment by riuson** [comment]
Ok, glad to hear that.
