### ISSUE TITLE
Cannot build on Mac OS 10.12.4

### ISSUE THREAD

**Issue by sbfreddie** [riuson/lcd-image-converter#45]
Hello:
While trying to build this app using qmake according to your instructions, qmake gives this error:
RCC: Error in 'resources/resources.qrc': Cannot find file 'lcd-image-converter-ru.qm'

What am I doing wrong?

Thanks,
Ed

**Comment by riuson** [comment]
Hello.
Its OK. This file compiles from lcd-image-converter-ru.qm with `make` command.
For example, see at lines 397 and 403 from [this build log](https://travis-ci.org/riuson/lcd-image-converter/jobs/213045850).
This file (qm) not included because it is binary file what often changed.

**Comment by dimka-rs** [comment]
Same problem with linux:
`RCC: Error in 'resources/resources.qrc': Cannot find file 'lcd-image-converter-ru.qm'`
How do you build app correctly then?

**Comment by riuson** [comment]
This message appears after the start of the qmake?
Have you tried running make after this?

**Comment by dimka-rs** [comment]
Agh, got it, Makefile is created anyway. Probably you should mention in readme that this error is safe to ignore. Thank you!

**Comment by riuson** [comment]
This was mentioned in this topic above and docs: https://www.riuson.com/lcd-image-converter/others/build-from-sources
