### ISSUE TITLE
Generated files include extra empty lines

### ISSUE THREAD

**Issue by antoniovazquezblanco** [riuson/lcd-image-converter#48]
Generated source code files have empty lines before the header and in between the header and the `block_images_table` section.

Can they be removed to better fit the templates?

**Comment by riuson** [comment]
There is no extra spaces.
Just remove _new line_ characters from required strings.
Change code from
```
...
#include <stdint.h>
$(end_block_header)

$(start_block_images_table)
#if (0x0$(out_char_code_sim) == 0x0)
...
```
to
```
...
#include <stdint.h>$(end_block_header)

$(start_block_images_table)#if (0x0$(out_char_code_sim) == 0x0)
...
```

Because `$(tag)` just removed from text, but empty lines are keeped.
