### ISSUE TITLE
Is it possible to change the bit endianness?

### ISSUE THREAD

**Issue by techtoys** [riuson/lcd-image-converter#53]
Hi

I have a display with endianness as follows:
if a pattern  10110101 is wanted at the top left corner, we need to send 0xAD but not 0xB5.
That means the bit position is reversed from little-endianness. 

I tried to change it from Options>Image>Big-Endian but there is no change on the bit position.

Is there any way to do the bit reverse from LCD Image Converter?

John

**Comment by riuson** [comment]
Bit's order can be changed on the **Reordering** tab.
https://www.riuson.com/lcd-image-converter/options/conversion/reordering

**Comment by techtoys** [comment]
Thank you
