### ISSUE TITLE
What algorithm did you use to solve the distortion caused by the conversion of 24-bit image to 565-bit image?

### ISSUE THREAD

**Issue by liefyuan** [riuson/lcd-image-converter#55]
After the application, I found that your conversion effect is particularly good. What algorithm did you use to solve the distortion caused by the conversion of 24-bit image to 565-bit image?

**Comment by riuson** [comment]
I don't use any specific algorithms.
R[7-0] G[7-0] B [7-0] reduced to R[7-3] G[7-2] B [7-3]
