### ISSUE TITLE
CLI to convert images with pre-defined template

### ISSUE THREAD

**Issue by dsalychev** [riuson/lcd-image-converter#57]
Hi,

I wonder which way would be the easiest one to have a command-line interface for lcd-image-converter to be called for a single image to be converted and a template for images? Something like:
    
```
    $ ./lcd-image-converter  -i scene.png -t image_template.tmpl -o scene.c
```

**Comment by dsalychev** [comment]
I'm looking for a place in code where to start hacking from, no more.

**Comment by riuson** [comment]
Hi,
I don't understand. You are have found the command already. What you want to hack?

**Comment by dsalychev** [comment]
Ah, it makes sense :) I haven't seen that page. Thanks!
