### ISSUE TITLE
Can't build lcd-converter on macOS.

### ISSUE THREAD

**Issue by DiamondWrist** [riuson/lcd-image-converter#58]
I have installed qt5 by brew. Then I called "qmake" and watched this error
<img width="572" alt="image" src="https://user-images.githubusercontent.com/37808972/88371878-8bf6fa80-cd9d-11ea-983a-ed5d331662ea.png">

**Comment by riuson** [comment]
Add `#include <QPainterPath>` to header's section of toolfill.cpp

**Comment by DiamondWrist** [comment]
@riuson thx a lot!!!! Build was successful.

**Comment by riuson** [comment]
Fixed at revision 52ca14a0aa93cd38cf6b3852b94122cc5c0ef157
