### ISSUE TITLE
conversion preset deleted

### ISSUE THREAD

**Issue by vintan** [riuson/lcd-image-converter#62]
I am using the lcd-image-converter-20190317 executable on Windows.
Accidentally I removed the monochrome conversion preset. Now I am unable get it even after the fresh .exe
I have tried clearing Temp folder.

**Comment by riuson** [comment]
Look to command line options:
https://lcd-image-converter.riuson.com/en/docs/others/command-line/

**Comment by vintan** [comment]
> Look to command line option **config-initialize**
> https://lcd-image-converter.riuson.com/en/docs/others/command-line/

Thank you for you quick response..
Re-initialized the configurations.
