### ISSUE TITLE
"Split to rows" only works when "Bands" is disabled

### ISSUE THREAD

**Issue by zaprodk** [riuson/lcd-image-converter#65]
Hi.
Your program has been very helpful for me in converting bitmap images for a SSD1325-based OLED-display i'm working with.

Standard setup with Grayscale-4 produces nice results, arrays nicely printed in lines, even "human readable" in the editor, ready to copy to my source code fiile.

Now i've decided to turn my OLED 90 degrees on it's side, and this means i will need pixels in "bands".

When bands is selected, "Split to rows" is no longer working. It gives me either a byte per line or one long line with no line breaks. A bit cumbersome with big data arrays (source image is 58x88 pixels)
Am i overlooking something or is this a bug?
Thanks!
I'm running version 466b2e2 on Windows 10.

**Comment by riuson** [comment]
Hello,
I can't reproduce problem neither on 466b2e23a03ccf57597fbae90b918ee75a3ebf5e (12 Oct 2016) or actual code.
Please try [latest version](https://sourceforge.net/projects/lcd-image-converter/files/).
If the problem persists, please provide more details to reproduce it (xml document with image, exported preset in xml).
