### ISSUE TITLE
Zig-zag conversion

### ISSUE THREAD

**Issue by TriBallscom** [riuson/lcd-image-converter#66]
Hi,

Most people who build matrix led setups from led strips use a zig-zag setup, it would be nice if the conversion could do a zig-zag scan.

**Comment by riuson** [comment]
Hello,
It is already possible with custom scan script.

**Comment by TriBallscom** [comment]
I couldn't find how to customize the script. 
It would be very helpful :)

**Comment by TriBallscom** [comment]
Ow stupid, never mind..
