### ISSUE TITLE
некорректное использование неполного типа «const class QPainterPath»

### ISSUE THREAD

**Issue by klenSA** [riuson/lcd-image-converter#72]
ubuntu 20.04
gcc:
Целевая архитектура: x86_64-kgp-linux-gnu
Параметры конфигурации: ../../src/gcc/configure -v --prefix=/klen/tools/x86_64-kgp-linux-gnu-znver2-avx2 --target=x86_64-kgp-linux-gnu --host=x86_64-kgp-linux-gnu --build=x86_64-kgp-linux-gnu --enable-gold --with-pic --disable-bootstrap --enable-lto --enable-languages=c,c++,lto --enable-plugins --disable-libstdcxx-debug --disable-libstdcxx-pch --enable-nls --enable-static --disable-shared --with-demangler-in-ld --enable-symvers --enable-visibility --enable-libdecbumber --enable-libquadmath --enable-libsanitizer --enable-libssp --enable-libmpx --disable-multilib --enable-decimal-float=yes --enable-version-specific-runtime-libs --with-pkgversion='Klen'\''s GNU package (KGP) for target::x86_64-kgp-linux-gnu-znver2-avx2 @ host::x86_64-kgp-linux-gnu << ARONIA >>' --with-local-prefix=/klen/tools/x86_64-kgp-linux-gnu-znver2-avx2 CFLAGS='-mtune=znver2 -march=znver2 -mavx2 -pipe -g0 -Ofast -fPIC -fgraphite -ffunction-sections -fdata-sections ' CXXFLAGS='-mtune=znver2 -march=znver2 -mavx2 -pipe -g0 -Ofast -fPIC -fgraphite -ffunction-sections -fdata-sections ' LTCFLAGS='-mtune=znver2 -march=znver2 -mavx2 -pipe -g0 -Ofast -fPIC -fgraphite -ffunction-sections -fdata-sections  -all-static -static-libstdc++ -static-libgcc' LDFLAGS='-mtune=znver2 -march=znver2 -mavx2 -pipe -g0 -Ofast -fPIC -fgraphite -ffunction-sections -fdata-sections               -static-libstdc++ -static-libgcc  -Wl,-gc-sections '
Модель многопоточности: posix
Supported LTO compression algorithms: zlib
gcc версия 12.0.0 20211001 (experimental) (Klen's GNU package (KGP) for target::x86_64-kgp-linux-gnu-znver2-avx2 @ host::x86_64-kgp-linux-gnu << ARONIA >>)

`git --git-dir /tmp/lcd-image-converter-master/.git log --pretty=format:"#define GIT_REVISION \"%H\"%n#define GIT_REVISION_ABBR \"%h\"%n#define GIT_COMMIT_ADATE \"%ai\"%n#define GIT_COMMIT_AT %at%n" -1 > /tmp/lcd-image-converter-master/resources/revision.h
g++ -c -pipe -std=c++11 -O2 -std=gnu++11 -Wall -Wextra -D_REENTRANT -fPIC -DQT_MAJOR_VERSION=5 -DQT_MINOR_VERSION=15 -DQT_PATCH_VERSION=2 -DQT_NO_DEBUG -DQT_SVG_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_XML_LIB -DQT_XMLPATTERNS_LIB -DQT_QML_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -I. -I. -Iclasses -Iclasses/action-handlers -Iclasses/compression -Iclasses/data -Iclasses/cmdline -Iclasses/imageeditor -Iclasses/operations -Iclasses/status -Iclasses/parser -Iclasses/parser/convert -I/tmp/lcd-image-converter-master/classes/preview-models -Iclasses/settings -Iclasses/settings/presets -Icontrols -Icontrols/about -Icontrols/fonts/font-changed -Icontrols/fonts/font-editor -Icontrols/fonts/font-new -Icontrols/fonts/font-preview -Icontrols/fonts/font-range -Icontrols/images -Icontrols/imageeditor -Icontrols/main -Icontrols/resize -Icontrols/save-changes -Icontrols/start -Icontrols/setup -Icontrols/setup/parts -Icontrols/setup/parts/font -Icontrols/setup/parts/image -Icontrols/setup/parts/matrix -Icontrols/setup/parts/prepare -Icontrols/setup/parts/prepare/scanning -Icontrols/setup/parts/prepare/preprocessing -Icontrols/setup/parts/reordering -Icontrols/setup/parts/templates -Icontrols/updates -Iinterfaces -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtSvg -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtXml -I/usr/include/x86_64-linux-gnu/qt5/QtXmlPatterns -I/usr/include/x86_64-linux-gnu/qt5/QtQml -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -Irelease/linux/.moc -Irelease/linux/.uic -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -o release/linux/.obj/toolfill.o classes/imageeditor/toolfill.cpp
classes/imageeditor/toolfill.cpp: В функции-члене «bool ImageEditor::Tools::ToolFill::fillArea(int, int, const QColor&)»:
classes/imageeditor/toolfill.cpp:194:41: ошибка: некорректное использование неполного типа «const class QPainterPath»
  194 |     if (!this->mParameters->selectedPath().isEmpty()) {
      |          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~
In file included from /usr/include/x86_64-linux-gnu/qt5/QtGui/qtransform.h:43,
                 from /usr/include/x86_64-linux-gnu/qt5/QtGui/qimage.h:48,
                 from /usr/include/x86_64-linux-gnu/qt5/QtGui/QImage:1,
                 from classes/imageeditor/toolfill.h:24,
                 from classes/imageeditor/toolfill.cpp:20:
/usr/include/x86_64-linux-gnu/qt5/QtGui/qmatrix.h:54:7: замечание: forward декларация «class QPainterPath»
   54 | class QPainterPath;
      |       ^~~~~~~~~~~~
make: *** [Makefile:1987: release/linux/.obj/toolfill.o] Ошибка 1
`

**Comment by riuson** [comment]
Подобное было в #58 .
Сейчас установил Ubuntu 20.04, Qt5 и GCC 9.3.0 из репозитория, всё собирается нормально.
