### ISSUE TITLE
Lost presets

### ISSUE THREAD

**Issue by RicardoCSR** [riuson/lcd-image-converter#73]
Hi Riuson,
I am using the program LCD Image Converter to use some image to my project it was perfect but I lost the default preset that i used the COLOR RGB565 so I "reinstall" the program, but still only with the remaining options, do you know who to fix it or reset that part of the program?

thank you

**Comment by riuson** [comment]
Hello,
Use command line: https://lcd-image-converter.riuson.com/en/docs/others/command-line/
