### ISSUE TITLE
Completely broken

### ISSUE THREAD

**Issue by InformaticsProject** [riuson/lcd-image-converter#76]
Import image - > Nothing
New image -> It's too small
Resize -> you can't just type in your size that would be too easy, instead type in by how much you want to EXTEND your size. Also broken doesn't work on the y axis???? 
Fill tool -> Does nothing
Select anything -> sticky select box
Drag in image  -> nope
Do anything -> Colors disappear
Try to draw -> Whole canvas disappears?????

wtf is this

**Comment by riuson** [comment]
If you don't want to learn the interface of a program and expect it to work like something you know, then use exactly the program that you know well.
