### ISSUE TITLE
lcd-image-converter

### ISSUE THREAD

**Issue by gordonpow** [riuson/lcd-image-converter#81]
Hello, I accidentally deleted the color r6g5b6 in the preset option of the operation. Where can I find this file?

**Comment by riuson** [comment]
Hello, gordonpow.
 
Use  --config-initialize  command line argument:
Command line | LCD Image Converter (riuson.com) 

Вы писали 7 сентября 2023 г., 15:15:47:

> Hello, I accidentally deleted the color r6g5b6 in the preset option of the operation. Where can I find this file?
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you are subscribed to this thread.

-- 
С уважением,
 Vladimir                         ***@***.***

**Comment by riuson** [comment]
Hello,
Use  `--config-initialize`  [command line](https://lcd-image-converter.riuson.com/en/docs/others/command-line/) argument.

**Comment by gordonpow** [comment]
Thank you, I have solved my problem, thank you for taking the time to reply
to my message.

Vladimir ***@***.***> 於 2023年9月8日 週五 00:09 寫道：
